@startuml
class Molde
class Redondo 
class Cuadrado
class Corazon
class Pastel {
    -Capa capa []
}
class Vainilla
class Fresa
class Decoracion{
    +Pastel : Decorar(color)
} 
class Chispa
class Color
class Chocolate 
class Cobertura {
    +Pastel : Decorar(color)
}
class Rojo
class Verde
class Rosa
class Cafe
class Relleno{
    +Pastel : Decorar(sabor)
}
class Crema 
class Mermelada
class Cereza
class Utencilio{
    +Pastel : Ayudar(forma)
}
class Espatula
class Horno
class Transportadora
class Caja 
class Personaje {
    -Pedido pedido
}
class Pedido{
    -Pastel pastel 
    }
class Capa 

Redondo--|>Molde
Redondo--|>Molde
Cuadrado --|>Molde 
Corazon --|> Molde 
vainilla--|>pastel
Chocolate--|>pastel
Fresa--|>Pastel
Chispa--|>Decoracion 
Chocolate--|>Chispa
Color--|>Chispa
Rojo--|>Cobertura
Verde--|>Cobertura
Rosa--|>Cobertura
Cafe--|>Cobertura 
Crema--|>Relleno 
Mermelada --|>Relleno 
Cereza--|>Decoracion
Espatula--|>Utencilio
Horno--|>Utencilio
Transportadora--|>Utencilio
Caja-->Utencilio
Pastel "1" o--"1,3" Molde
Pastel o-- Decoracion
Pastel o-- Cobertura
Pastel o-- Relleno 
personaje "1"*-- "1,4"Pedido
Pedido *-- Pastel 
Pastel "1"*--"1,3" Capa 
Pastel "1" o--"1,5"Utencilio 

@enduml