@startuml
class molde
class redondo 
class cuadrado
class corazon
class pastel 
class vainilla
class fresa
class decoracion 
class chispa
class color
class chocolate 
class cobertura 
class rojo
class verde
class rosa
class cafe
class relleno 
class crema 
class mermelada
class cereza
class utencilio 
class espatula
class horno 
class transportadora
class caja 
class personaje 
class pedido
class capa 

redondo-->molde
redondo-->molde
cuadrado -->molde 
corazon --> molde 
vainilla-->pastel
chocolate-->pastel
fresa-->pastel
chispa-->decoracion 
chocolate-->chispa
color-->chispa
rojo-->cobertura
verde-->cobertura
rosa-->cobertura
cafe->cobertura 
crema-->relleno 
mermelada -->relleno
cereza-->decoracion
espatula-->utencilio
horno-->utencilio
transportadora-->utencilio
caja-->utencilio
pastel o--"1,3" molde
pastel o-- decoracion
pastel o-- cobertura
pastel o-- relleno 
personaje *-- "1,4"pedido
pedido *-- pastel 
pastel *--"1,3" capa 
pastel o--"1,5"utencilio 

@enduml